
BNFRepeat		::=
	[
		#GetChar(BNFREPEATCHARS):<Simple>
	|
		BNFFullRepeat
	]:!Need
;

BNFFullRepeat	::=
	>Ignore(BNFLIgnore)
	[
		'{'
		>Force("Incomprehensive repeat values")
		[
			BNFRepeatCple
			[ ',' CChar:<Sep> ]?
			'}'
		|
			BNFRepeatSple
			[ ',' CChar:<Sep> ]?
			'}'
		]
	]
;

BNFRepeatSple	::=
	[
		#GetChar(BNFREPEATCHARS):<Simple>
	|
		#Integer(+):<FixNum>
	]
;

BNFRepeatCple	::=
	#Integer(+)?:<Min>
	','
	#Integer(+)?:<Max>
;
