
BNFTreeSave		::=
	':'
	>Ignore(BNFLIgnore)
	>NoIgnore
	[
		BNFTreeSaveNode:<Type "Node">
	|
		BNFTreeSaveAttr:<Type "Attr">
	]
;

BNFTreeSaveNode	::=
	'!'?:<NoValue '1'>
	>NoIgnore Identifier:<Name>
	>NoIgnore '.'?:<WithLine '1'>
;

BNFTreeSaveAttr	::=
	'<'
	Identifier:<Name>
	BNFLitteral?:<WithValue '1'>
	>NoIgnore
	>Force("Expecting '>' to end Attr definition") '>'
;