/*
  File created by Salomon BRYS : salomon . brys @ gmail . com
  This file is under TzLicence which is a MPL / LGPL / GPL Licence with some restriction.
  YOU MUST NOT USE THIS FILE FOR ANY COMERCIAL USE WITHOUT THE PERMISSION OF IT'S AUTHOR.
*/

BNFREPEATCHARS	= "?+*";

@Import("BNFIgnore.bnf");
@Import("BNFBase.bnf");
@Import("BNFTzBase.bnf");
@Import("BNFLitteral.bnf");
@Import("BNFRepeat.bnf");
@Import("BNFTreeSave.bnf");
@Import("BNFGroup.bnf");

BNF				::=
	>Ignore(BNFIgnore)
	>Force("Could not parse rules")
	[
		[
			BNFRule:Rule.
		|
			BNFString:!String.
		|
			BNFTzInstruction:!Instruction.
		]*
		>Force("Expected end of file") EndOfParse
	]
;

