#include "Opcodes.h"

#define CODENAME(c, a)	{c, #c, a}

namespace SoParse
{
	CodeName codeNames[] =
	{
		CODENAME(SAVE_CONTEXT, 0),
		CODENAME(RESTORE_CONTEXT, 0),
		CODENAME(CANCEL_CONTEXT, 0),
		CODENAME(IGNORE, 0),
		CODENAME(SET_IGNORE, 1),
		CODENAME(READ_CHAR, 0),
		CODENAME(READ_A_CHAR, 2),
		CODENAME(READ_CHAR_RANGE, 2),
		CODENAME(READ_CHAR_IN, 1),
		CODENAME(SET_SF, 2),
		CODENAME(IF, 2),
		CODENAME(LOAD, 1),
		CODENAME(GO_BACK, 0),
		CODENAME(GO_TO, 1),
		CODENAME(RESTORE_CONTEXT_AND_GO_BACK, 0),
		CODENAME(CANCEL_CONTEXT_AND_GO_BACK, 0),
		{0, "!!!ERROR!!!", 0}
	};

}
